### PR TITLE
Modifications related to the needs of VC

### PR DESCRIPTION
**Pull request by XiaowenVC**
1. We need multiple instance of `Searcher`(with always the same index). So I exposed the constructor in public.
2. We need methods to unregister result and error listeners.

### CODE REVIEW

**Comment by PLNech** [comment]
Hi @XiaowenVC, thanks for your contribution!

- Multiple instance of `Searcher`: This is already being implemented in the [PR for multi indexing](https://github.com/algolia/instantsearch-android/pull/59), which is under review and should soon be released
- Add methods : 👍 

With this in mind, I'll close this PR as the former point has been implemented differently in #59, and will reopen one with only the latter change (2a11930).

**Comment by XiaowenVC** [comment]
@PLNech Our need is: for the same index, we need to have multiple instance of searcher. In https://github.com/algolia/instantsearch-android/pull/59, I read that the create() function always try to get instance by index name, so this does not conform to our need.

**Comment by PLNech** [comment]
Hi @XiaowenVC, actually you can either specify just the `indexName`, [or an `indexName` and a variant](https://github.com/algolia/instantsearch-android/blob/89d0c2efe3acb90b2a7bd2d9a93197da1227613e/instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java#L188) if you need several `Searchers` targeting the same index:
```java
searcherMain = Searcher.create(ALGOLIA_APP_ID, ALGOLIA_API_KEY, ALGOLIA_INDEX);
searcherTwo = Searcher.create(ALGOLIA_APP_ID, ALGOLIA_API_KEY, ALGOLIA_INDEX, "two");
```

Each searcher will be connected to the set of widgets that specify the same variant.

**Comment by PLNech** [comment]
@XiaowenVC: We released yesterday [v1.5.0](https://github.com/algolia/instantsearch-android/releases/tag/1.5.0), which ships multi-index capabilities (including several searchers).

With that in mind, I'm glad to accept your PR for 2a11930, but without 266c685. 

Can you merge your branch with the latest `master`, and rebase to remove 266c685? I'll be happy to merge this afterwards. 
(Alternatively, if you don't care about being reported as a contributor, I can simply cherry-pick 2a11930 myself and push it to master, so as you prefer 🙂)

**Comment by XiaowenVC** [comment]
@PLNech I prefer to make it simple, do a cherry-pick please.

**Comment by PLNech** [comment]
@XiaowenVC: done and released in [v1.6.0](https://github.com/algolia/instantsearch-android/releases/tag/1.6.0).

**Pull request closed without merging**
