### PR TITLE
Update/algoliacomponents

### PR DESCRIPTION
**Pull request by JonasBa**

### CODE REVIEW

**Comment by PLNech** [comment]
Deploy preview processing.

Built with commit 24dbf029ff2e169d844c464271b1cc649b7ff4dd

https://app.netlify.com/sites/instantsearch-android-preview/deploys/58e3643366867412c7eb0215

**Comment by JonasBa** [comment]
@PLNech I'll let you review, merge and deploy \o/

**Comment by PLNech** [comment]
@JonasBa when running the project locally, it seems we miss an asset:
image

**Comment by JonasBa** [comment]
@PLNech Good spot, I fixed it :)

**Pull request merged**
